### ISSUE TITLE
Small ghosting issue

### ISSUE THREAD

**Issue by Supwaii** [TheRhysWyrill/XBSX2#10]
So In manual hardware settings, the skip draw start & end go up by 50. It would be nice if it were possible too make it go up by 1’s, as some games there’s a ghosting issue. Thank you in advance for the awesome emulator! :) 

### Console
[Xbox One/Series X|S]

**Comment by gongo1440** [comment]
I still have the same problem and I just updated it right now it jumps from 0 to 50 instead of 
5-6-7-8-9-10 successively this would fix the problems that jak has the precursor legacy that the character has shadow problems.
![20220901_195000](https://user-images.githubusercontent.com/112668679/188031079-ba62f4dd-2eba-4810-b350-3924c734c359.jpg)

**Comment by TheRhysWyrill** [comment]
Not sure how that is, on my end Skipdraw increments by 1 as you requested, how did you update? Using the Appx from the Releases page?

**Comment by gongo1440** [comment]
the update got to my xbox when i activated the manual hardware setting the skipDraw start/end
they are in values ​​of 0 each one when I go to upload it they go up to 50 it would be better if they went up from 0 to 50 this is an example of what I am referring to look at the second method https://m.youtube.com/watch ?v=8c-UZ9fcsqI

**Comment by gongo1440** [comment]
here is an example what i mean look at the second method https://m.youtube.com/watch?v=8c-UZ9fcsqI
Instead of going up from 0 to 1 until reaching 50, it jumps from 0 to 50.
this would fix the problems i have with jak the precursor legacy and i have the latest update that arrived today on my xbox which includes the anti-blur feature

**Comment by Supwaii** [comment]
Yeah mine seems to still go from 0-50 I'm trying to play def jam but it has this ghost effect still

**Comment by gongo1440** [comment]
I already solved the problem I had with jak 1 the precursor legacy the skipdraw now I can put it from 0 to 1 the shadow problem in the games was solved now the skipdraw works correctly thank you very much the saga of jak 1-2-3 was my memory of childhood.
