### ISSUE TITLE
Problem with drifting left analogue 

### ISSUE THREAD

**Issue by Tuan83** [TheRhysWyrill/XBSX2#29]
Hi, 
I've just installed xbsx2 to my Xbox series x. 
I have problems with drifting analogue and I don't know what to do. I've tried with 3 different controllers and problem was the same. I've tried to uinstalled and delete all xbsx2 folder on my Xbox and installed it again. But problem still remained :( please help! 
[Xbox One/Series X|S]

**Comment by TheRhysWyrill** [comment]
> Hi, I've just installed xbsx2 to my Xbox series x. I have problems with drifting analogue and I don't know what to do. I've tried with 3 different controllers and problem was the same. I've tried to uinstalled and delete all xbsx2 folder on my Xbox and installed it again. But problem still remained :( please help! [Xbox One/Series X|S]

It's not a controller issue don't worry, this issue has since been fixed, the issue was due to the default value of Analog Sensitivity setting itself to 14000% for some reason, either wait for an update if you're on Retail or grab the msix file from the releases page if you're using Dev Mode for the fix.

**Comment by Tuan83** [comment]
Thank you for the info. I'm currently on retail mode. So I will need to wait for the update then.
