### ISSUE TITLE
Multiple bindings set for controllers

### ISSUE THREAD

**Issue by Acidragon** [TheRhysWyrill/XBSX2#3]
I have a lot of friends that I'm promoting toward your new program here as it allows them to play socom 2 online again. However they are saying they do not know how to set the crouch button to also act on another button (multiple bindings) because in socom (for playstation) they had pressure sensitive buttons. So you would hold triangle to prone but also tap triangle to crouch. Since there is no multiple bindings people cant do that which is terrible way to play socom online.

Would like to just have a way to set a button to multiple buttons

Be able to set the crouch button on socom to also be set to another button to be able to also tap to prone

Right now people can only prone but not crouch as well.

[Xbox One/Series X|S] - Will be a problem on both.

**Comment by TheRhysWyrill** [comment]
Appreciate you bringing this to my attention, there is an `Apply Pressure` option in the Controller settings but upon testing said option with SOCOM 2 it would appear that the default pressure sensitivity value is too high so it incorrectly registers what should be a tap as a hold instead, this has since been corrected and should be fixed with the next update however.

**Comment by Acidragon** [comment]
> Appreciate you bringing this to my attention, there is an `Apply Pressure` option in the Controller settings but upon testing said option with SOCOM 2 it would appear that the default pressure sensitivity value is too high so it incorrectly registers what should be a tap as a hold instead, this has since been corrected and should be fixed with the next update.

So....one of my friends brought to my attention maybe I worded it wrong what I was trying to convey. So I hope this clears it up.

"say we need to sacrifice a button to be a second triangle input
we need one triangle with a full press sens and 1 with a lower sens"

That way someone can press the prone button (triangle) to prone and then hit a different button (binded as triangle, but say L3) and with a lower sens let us crouch. Does that make sense?

**Comment by TheRhysWyrill** [comment]
I don't think that's feasible, there would be no way of splitting the 2 inputs from 1 button to 2 separate buttons, as I've said there's a `Apply Pressure` setting in the Controller settings, that would just need to be set to a button that isn't used for anything important (When I was testing I used L2) and when you hold that button and press a face button it would register the input as a tap instead of a hold, allowing the playing to Crouch in SOCOM 2.

**Comment by TheRhysWyrill** [comment]
@Acidragon Can you confirm whether this issue is solved with the latest release?

**Comment by TheRhysWyrill** [comment]
> > @Acidragon Can you confirm whether this issue is solved with the latest release?
> 
> Can you explain further? Did you create an option somewhere to re bind controllers somewhere or what exactly do they have to do?

You can't rebind the same input to 2 separate inputs, what they'll need to do is navigate to Controller Settings and bind the "Apply Pressure" setting to a key that's not used for much/anything important and then when they want to crouch they would need to hold the input they bound to "Apply Pressure" and press whichever button they have bound to Crouch/Prone (by default it would be Triangle/Y).
